# Specify version format
version: "{build}"

image: Visual Studio 2017

platform: x64

# specify custom environment variables
environment:
  CMAKE_TOOLCHAIN_FILE: -DCMAKE_TOOLCHAIN_FILE="C:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake"
  matrix:
    - CMAKE_GENERATOR: -G"Visual Studio 15 2017 Win64"
      CMAKE_TOOLCHAIN: -T"v141"

# build configuration, i.e. Debug, Release, etc.
configuration:
  - Debug
  - Release

# scripts that are called at very beginning, before repo cloning
init:
  - cmd: cmake --version
  - cmd: msbuild /version

# scripts that run after cloning repository
install:

  # update vcpkg
  - cmd: cd C:\tools\vcpkg
  - cmd: git pull
  - cmd: .\bootstrap-vcpkg.bat
  
  - if "%platform%"=="Win32" set VCPKG_ARCH=x86-windows
  - if "%platform%"=="x64"   set VCPKG_ARCH=x64-windows

  # remove outdated versions
  - cmd: vcpkg remove --outdated --recurse
  
  # install pacakges
  # ---- required dependencies: eigen3, libccd, fcl, assimp, boost
  - cmd: vcpkg update
  
  # install required dependencies
  - cmd: vcpkg install --recurse --triplet %VCPKG_ARCH% assimp boost-system boost-filesystem ccd eigen3 fcl
  
  # install optional dependencies
  #- vcpkg install --recurse --triplet %VCPKG_ARCH% bullet3 flann freeglut nlopt ode opengl osg tinyxml2 urdfdom
  #- vcpkg install ipopt:%VCPKG_ARCH%
  
  - vcpkg integrate install
  
  - cmd: md build
  - cmd: cd build
  - cmd: cmake %CMAKE_GENERATOR% -DCMAKE_BUILD_TYPE=%configuration% %CMAKE_TOOLCHAIN_FILE% %CMAKE_TOOLCHAIN% ..
  
# preserve contents of selected directories and files across project builds
cache:
  #- C:\tools\vcpkg\installed -> .appveyor.yml

build: off
