# Specify version format
version: "{build}"

# specify custom environment variables
environment:
  matrix:
    - image: Visual Studio 2017
      platform: x64
      GENERATOR: Visual Studio 15 2017 Win64
      LLVM_TOOLCHAIN: LLVM-vs2015

    - image: Visual Studio 2017
      platform: Win32
      GENERATOR: Visual Studio 15 2017
      LLVM_TOOLCHAIN: LLVM-vs2015

    - image: Visual Studio 2015
      platform: x64
      GENERATOR: Visual Studio 14 2015 Win64
      LLVM_TOOLCHAIN: LLVM-vs2014

    - image: Visual Studio 2015
      platform: Win32
      GENERATOR: Visual Studio 14 2015
      LLVM_TOOLCHAIN: LLVM-vs2014

# build configuration, i.e. Debug, Release, etc.
configuration:
  - Debug
  - Release

# scripts that are called at very beginning, before repo cloning
init:
  - cmd: cmake --version
  - cmd: msbuild /version

# scripts that run after cloning repository
install:
  - if "%platform%"=="Win32" set VCPKG_ARCH=x86-windows
  - if "%platform%"=="x64"   set VCPKG_ARCH=x64-windows

  # install pacakges
  # ---- required dependencies: eigen3, libccd, fcl, assimp, boost
  - vcpkg update
  - vcpkg install eigen3:%VCPKG_ARCH%
  #- vcpkg install ccd:%VCPKG_ARCH%
  #- vcpkg install fcl:%VCPKG_ARCH%
  #- vcpkg install assimp:%VCPKG_ARCH%
  #- vcpkg install boost:%VCPKG_ARCH%
  # ---- optional dependencies: nlopt, ipopt, bullet3, ode, flann, tinyxml2, urdfdom_headers, urdfdom, opengl, freeglut, osg
  #- vcpkg install nlopt:%VCPKG_ARCH%
  #- vcpkg install ipopt:%VCPKG_ARCH%
  #- vcpkg install bullet3:%VCPKG_ARCH%
  #- vcpkg install ode:%VCPKG_ARCH%
  #- vcpkg install flann:%VCPKG_ARCH%
  #- vcpkg install tinyxml2:%VCPKG_ARCH%
  #- vcpkg install urdfdom_headers:%VCPKG_ARCH%
  #- vcpkg install urdfdom:%VCPKG_ARCH%
  #- vcpkg install opengl:%VCPKG_ARCH%
  #- vcpkg install freeglut:%VCPKG_ARCH%
  #- vcpkg install osg:%VCPKG_ARCH%
  
  - vcpkg integrate install
  
  - cmd: md build
  - cmd: cd build
  - cmd: cmake -G "%GENERATOR%" -DCMAKE_BUILD_TYPE=%configuration% "-DCMAKE_TOOLCHAIN_FILE=C:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake" -T"%LLVM_TOOLCHAIN%" ..
  
# preserve contents of selected directories and files across project builds
cache:
  - C:\projects\vcpkg\installed -> .appveyor.yml
  - C:\projects\vcpkg\packages -> .appveyor.yml

build: off
